CREATE DATABASE BIBLIOTECA

USE BIBLIOTECA

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY IDENTITY (1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	SEXO BIT NOT NULL,
	CEDULA VARCHAR(50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	OCUPACION BIT NOT NULL
)
CREATE TABLE RECURSO(
	ID INT PRIMARY KEY IDENTITY (1,1),
	RECURSO VARCHAR(50) NOT NULL
)

CREATE TABLE RECURSOS(
	ID INT PRIMARY KEY IDENTITY (1,1),
	ID_RECURSO INT FOREIGN KEY REFERENCES RECURSO(ID) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	UBICACION VARCHAR(50) NOT NULL,
	DISPONIBILIDAD BIT NOT NULL
)

CREATE TABLE RESERVAS(
	ID INT PRIMARY KEY IDENTITY (1,1),
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL,
	ID_RECURSO INT FOREIGN KEY REFERENCES  RECURSOS(ID) NOT NULL,
	FECHA_INICIO DATETIME NOT NULL,
	FECHA_FIN DATETIME NOT NULL
)
